### ISSUE TITLE
Garbage value loaded into CR3 when no task is running and keyboard interrupt occurs.

### ISSUE THREAD

**Issue by yuvraj1803** [nibblebits/PeachOS#19]
In src/keyboard/classic.c: line 92

task_page() is called.

When there is no task running, and the keyboard interrupt occurs, current_task is NULL/garbage.
CR3 is loaded with some garbage value causing unexpected behaviour.

Regards,
Yuvraj Sakshith

**Comment by yuvraj1803** [comment]
**In src/keyboard/classic.c**

<img width="1587" alt="Screenshot 2023-05-04 at 5 43 40 PM" src="https://user-images.githubusercontent.com/37622719/236201288-6b29afc3-b789-4231-a000-5a10fa4ac4c4.png">

**In line 92, task_page() is called.**

**In src/task/task.c**

<img width="625" alt="Screenshot 2023-05-04 at 5 44 03 PM" src="https://user-images.githubusercontent.com/37622719/236201469-9c91a17a-e12e-416f-a031-45514dfa8a08.png">

**In line 191, task_page() calls task_switch(current_task). But current_task can be NULL, because,...**

<img width="672" alt="Screenshot 2023-05-04 at 5 44 28 PM" src="https://user-images.githubusercontent.com/37622719/236201729-037db551-f2b9-4a14-b041-3ac6888f1763.png">

**In src/task/task.c:13 It was initialised as NULL.**

**This leads to an invalid page directory being loaded (see below)**
<img width="733" alt="Screenshot 2023-05-04 at 5 45 11 PM" src="https://user-images.githubusercontent.com/37622719/236202236-b88f6391-caf4-4828-b7ef-0b04885a6854.png">

**task is NULL, and task->page_directory is being loaded into CR3**

I hope this makes it clear :)

**Comment by yuvraj1803** [comment]
Suggested fix:

**In src/keyboard/classic.c:**

**Line 92:** `if(task_current()) task_page();`

**Comment by nibblebits** [comment]
Hello,
I don't believe this to be an issue because their isnt a senario where their cant be a task. If I remember correctly if the program crashes a new task is spawned, you are welcome to put a panic in your code if you wish but I don't beleive this is neccessary. I did write the kernel a while ago so if you believe I'm wrong on that if you can show me I can look into it further, however I do not see a cause for a concern in this regard given that their will always be a task running. Even when a task is killed I believe we spawn another task 

Thanks
Dan
